workflows:
  ios-demo-build:
    name: iOS Flutter Demo Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: ios/Runner.xcodeproj
        XCODE_SCHEME: Runner
        BUNDLE_ID: com.example.loginUi
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app for simulator
        script: |
          flutter build ios --simulator --debug
    artifacts:
      - build/ios/iphonesimulator/Runner.app
    publishing:
      email:
        recipients:
          - your-email@example.com
